pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Pulling Code From Version Control Repository...'
            }
       stage('Build Docker Image') {
    steps {
        script {
            // Ensure you are in the directory where Dockerfile exists
            sh 'docker build -t fraud-prediction-api:latest .'
        }
    }
}
        }
        stage('Test Pipeline API') {
            steps {
                echo 'Executing endpoint integration testing...'
            }
        }
        stage('Kubernetes Deployment') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
            }
        }
    }
}