pipeline {
    agent any
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Starting...'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t fraud-prediction-api:latest .'
            }
        }
        stage('Test Pipeline API') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Kubernetes Deployment') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
            }
        }
    }
}
